{% set name = "umap-learn" %}
{% set version = "0.5.5" %}
{% set sha256 = "c54d607364413eade968b73ba07c8b3ea14412817f53cd07b6f720ac957293c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and py27 or win32]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python <3.12                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - pip
  run:
    - python <3.12
    - setuptools
    - numpy >=1.17
    - numba >=0.51.2
    - scikit-learn >=0.22
    - scipy >=1.3.1
    - tbb >=2019.0
    - pynndescent >=0.5
    - tqdm

test:
  imports:
    - umap

about:
  home: http://github.com/lmcinnes/umap
  license: BSD-2-Clause
  license_family: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Uniform Manifold Approximation and Projection

  description: |
    umap-learn provides the UMAP manifold based dimension reduction
    algorithm. The package provides an sklearn compatible interface
    to t-SNE like dimension reduction technique that has better 
    runtime performance than t-SNE and often preserves more global
    structure than t-SNE.
  dev_url: https://github.com/lmcinnes/umap

extra:
  recipe-maintainers:
    - lmcinnes
