{% set name = "umap-learn" %}
{% set version = "0.5.0" %}
{% set sha256 = "769c50629871384e85e952ad6f7086c49895f0390e1da8d2b2d7c60ad03a0ed0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py27 or win32]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - numpy >=1.17
    - numba >=0.46,!=0.47
    - scikit-learn >=0.20
    - scipy >=1.3.1
    - tbb >=2019.0

test:
  imports:
    - umap

about:
  home: http://github.com/lmcinnes/umap
  license: BSD-2-Clause
  license_family: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Uniform Manifold Approximation and Projection

  description: |
    umap-learn provides the UMAP manifold based dimension reduction
    algorithm. The package provides an sklearn compatible interface
    to t-SNE like dimension reduction technique that has better 
    runtime performacne than t-SNE and often preserves more global
    structure than t-SNE.
  dev_url: https://github.com/lmcinnes/umap

extra:
  recipe-maintainers:
    - lmcinnes
